export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_ALL_COMMENTS_FOR_POST_SUCCESS = 'GET_ALL_COMMENTS_FOR_POST_SUCCESS';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS_SUCCESS';