export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS';
export const GET_POST_SUCCESS = 'GET_POST';
export const GET_ALL_COMMENTS_FOR_POST_SUCCESS = 'GET_ALL_COMMENTS_FOR_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';